apiVersion: apps/v1
kind: Deployment
metadata:
  name: task2-deployment
  labels:
    app: task2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task2
  template:
    metadata:
      labels:
         app: task2
    spec:
      containers:
      - name: scaletestapp
        image: shestera/scaletestapp:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 15Mi # вопреки заданию пришлось поставить столько, иначе приложение не достигало максимального потребления памяти
