http {
   # Настройка зоны ограничение количества запросов
   limit_req_zone $binary_remote_addr zone=ratelimit:10m rate=10r/m
   # HTTP-код ответа при превышении заданного порога
   limit_req_status 429
   # Устанавливаем зону ограничения скорости на все серверы
   limit_req zone=ratelimit

   # Настройка upstream для балансировки нагрузки
   upstream backend_servers {
       server backend1.example.com;
       server backend2.example.com;
       server backend3.example.com;
   }

   server {
       listen 80;

       location / {
           proxy_pass http://backend_servers;
       }

   }
}