# Клиент
type Client {
  # Идентификатор клиента (обязательный)
  id: String!
  # Наименование клиента (обязательный)
  name: String!
  # Возраст клиента (из swagger не очень понятно, обязательный он или нет, определил как необязательный атрибут)
  age: Int
  # Документы клиента
  documents: [Document!]
  # Родственники клиента
  relatives: [Relative!]
}

# Документ клиента
type Document {
  # Идентификатор документа (обязательный)
  id: String!
  # Тип документа (обязательный)
  type: String!
  # Номер документа (обязательный)
  number: String!
  # Дата выдачи документа (обязательный)
  issueDate: String!
  # Дата окончания срока действия документа (кажется, что необязательный)
  expiryDate: String
}

# Родственник клиента
type Relative {
  # Идентификатор субъекта (обязательный)
  id: String!
  # Тип отношений (обязательный)
  relationType: String!
  # Наименование субъекта (обязательный)
  name: String!
  # Возраст субъекта (из swagger не очень понятно, обязательный он или нет, определил как необязательный атрибут)
  age: Int
}


# Root query
type Query {
  # Возвращает информацию о клиенте
  client(
	id: String!
  ): Client
}